[package]
name = "glboot"
version = "0.1.0"
authors = ["Jonatas <jbmagalhaes28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.37.0"
imgui = "0.3.0"
imgui-opengl-renderer = "0.7.0"
cgmath = "0.17.0"
image = "0.23.4"
